python/tk_desktop/project_commands_model.py
python/tk_desktop/project_model.py

Previously we used the event log to help track recent app launches and recently accessed projects per user. This was causing performance issues due to the additional queries required to calculate this information (especially on the event log which can be very slow).
With this change, we now track recent app launches using the [settings module in the Shotgun Utils Framework](http://developer.shotgunsoftware.com/tk-framework-shotgunutils/settings.html). These are tracked for the user on a per-project level and are unique to each machine the user is using. Recently accessed Projects are now solely tracked by the `Project.last_accessed_by_currrent_user` field on the Project in Shotgun. This information is updated whenever the Project is accessed via SG Desktop as well.

For #29128: Don't use the event log for tracking recent activity

---

python/tk_desktop/desktop_engine_project_implementation.py
python/tk_desktop/project_commands_model.py

* Adds a proxy function for getting engine settings from the project environment.
* Uses the existing `parent()` settings interface from `desktop_window` instead of reimplementing settings management. 
* This also changes the way we're storing the settings to be more in line with other project-specific settings like `project_expanded_state`. Instead of storing settings in the project scope, we're storing it in the site scope using the project `id` as an identifier (eg. `project_recent_apps.161`). Combined with the using the `parent()` implementation, this solves the issue where the settings module was using the site environment to determine the project scope - which was incorrect.

for #29128: add proxy function to get engine settings for project env

---

info.yml
python/tk_desktop/desktop_window.py
python/tk_desktop/no_apps_installed_overlay.py

Updates required to retrieve original source images uploaded for thumbnails. The primary reason for this update was to get the icons associated with Software entities to display with transparency in the NoAppsInstalledOverlay widget. The implementation attempts to handle older versions of tk-core and tk-framework-shotgunutils that may not have this feature implemented.

For #39292, Support transparent Software entity icons

---

python/tk_desktop/desktop_engine_project_implementation.py
python/tk_desktop/desktop_engine_site_implementation.py

If no collapse rules have been determined for a command, check for input `group` and `group_default` properties. If present, these will be treated the same as collapse rules. The current implementation does not actually support the `group_default` property, as this is determined at a much lower level by the project_commands_model.

#40549, Support 'group' and 'group_default' command properties

---

python/tk_desktop/desktop_engine_project_implementation.py
python/tk_desktop/desktop_engine_site_implementation.py
python/tk_desktop/desktop_window.py
python/tk_desktop/project_commands_model.py

Implementation to support the `group_default` property value passed into the `engine.register_command()` method.  Also fixes an issue where icons were not being loaded for non-default commands in the RECENTS group.

40549 improved grouping support

---

engine.py

This fixes an issue where the Shotgun Desktop on certain computers will show an empty dialog the first time an app in launched.

Fix python window appears when launching some apps from SG Desktop

---

python/tk_desktop/desktop_engine_site_implementation.py

This minor change applies toolkit standard stylings to custom panels.
Previously, styling for custom panels was not being picked up, resulting in for example the Shotgun panel running as a tab inside of desktop looking non-standard. This fix resolves this issue:

#43719: Standard styling for site level panels

---

engine.py
python/tk_desktop/communication_base.py
python/tk_desktop/desktop_engine_project_implementation.py
python/tk_desktop/desktop_engine_site_implementation.py
python/tk_desktop/desktop_window.py

The action follows these rules:
1. If TK_DEBUG is set in the environment, debug logging is always on and the menu action is disabled.
2. If the user previously used this menu action to turn debugging on or off, that is remembered in engine-level user settings and will be preserved when SG Desktop is relaunched.
3. If TK_DEBUG is not set in the environment and the user has not previously used this menu action to toggle debug logging on or off, the checked state of the action will match the global debug setting as reported by the LogManager.
The only bit here that is unfortunate is that QMenu in Qt4.x does not support showing tooltips for QActions. I've included tooltips anyway, as presumably someday this will be running in Qt 5.x and they'll just start showing properly.

For #43813: Adds a debug logging toggle action to the Advanced menu.

---

python/tk_desktop/desktop_engine_site_implementation.py
python/tk_desktop/desktop_window.py
python/tk_desktop/project_menu.py
python/tk_desktop/site_communication.py

This pull request fixes a project-related UI problem. If you select the reload and restart option from the project context menu in the top right, it will duplicate all the options in the menu.
The fix is about adding a new `proxy created hook` allowing resetting of some UI components (namely the project context menu) after engine and proxy have been reset. 
The main clear UI method is now split.

43269 desktop reload and restart menu item dupes

---

python/tk_desktop/desktop_window.py
python/tk_desktop/project_menu.py

I was trying to understand what was creating a radio button like behavior in the code but couldn't find anything. Until I realized that the radio-button-like behavior was done by simply recreating the options all of the time and 'checking' the user choice.
There are two distinct commits in this pull request:
- Fixes a bug introduced in the last commit
- Replace UI checkboxes with actual radio buttons.
The second one is really optional and up to reviewer. The change is just a visual one. The behavior remains the same.

43269 desktop reload and restart menu item dupes 2

---

python/tk_desktop/desktop_window.py
python/tk_desktop/project_menu.py

Moved the creation of the menu separator to the 'ProjectMenu.clear()' which was also renamed 'rese()' for clarity. On switching back and forth between a multi-configuration pipeline and a single configuration pipeline, a call to the 'ProjectMenu.clear()'  method would be made. The later clears the QT menu and the '_pipeline_configuration_separator' instance member would then reference a deleted QT object.

For #43269: Fix issue with single configuration pipeline

---

bootstrap.py
python/utils/bootstrap_utilities.py

The problem's result is that the connection from handle_error hangs on connect. The workaround is to make use of the same RPCProxy object that we already have at the time that the bootstrap is running.
The source of the problem appears to be either a client connection that doesn't actually close when it's asked to, or a server issue whereby it doesn't accept new connections when a connection is terminated. The workaround is to make use of an existing connection when we have one to use, and only try to create a new one to report errors when that's not possible. This resolves the bulk of the error reporting issues, which are most likely to occur when bootstrapping.

For #45989: Implements a workaround for an error reporting issue on Windows.

---

python/tk_desktop/desktop_window.py

This fixes an issue that arises when Toolkit can't create a descriptor for one of the available descriptors.

Addendum for #46567, background download of zipped configs

---

info.yml
python/tk_desktop/desktop_window.py
python/tk_desktop/loading_project_widget.py

- Refactors the code a bit to use the overlay widget from qtwidgets
- Handles missing tank name errors by providing a hyperlink to the project's page.

For #46757, gentler error when `tank_name` is not set.

---

python/tk_desktop/project_menu.py

When clearning the menu, do not remove the Jump To xxx action. This one gets turned on or off on demand.
Note that this only fixes the issue for classic configs. Bootstraped configs are running into an issue. 
The issue is simple. A path cache parent folder for a plugin based config is `p<project-id>c<pc-id>.<plugin-name>`. This means that every plugin has it's own copy of the path cache, therefore each plugin sync their updates in their own local path cache. Since desktop does not sync the path cache on startup, it is always empty, so the menu item will never appear.

For SG-6816, jump to project fix

---

python/tk_desktop/desktop_engine_project_implementation.py
python/utils/bootstrap_utilities.py

Fixes an issue where `tk-desktop` would not log the exception information over the proxy.
This PR fixes it, although I'm not sure if it is the best approach. The `record.exc_info` can't be pickled, and therefore can't be passed as a separate arg for the `_proxy_log` method to deal with , so I opted for formatting the traceback and combining it with the `record.msg`.
Example where error was raised in a core hook:
```
2019-11-29 17:02:52,438 [15022 ERROR sgtk.ext.tkimp2a7afea3ef6949d9b67ed01e069df98c.tk_desktop.site_communication] [PROXY] Exception raised while executing hook '/sg_toolkit/philscad/configs/garden_show/core/hooks/context_change.py'
File "/Users/philips1/Library/Caches/Shotgun/philscad/p89c1.basic.desktop/cfg/install/core/python/tank/pipelineconfig.py", line 1217, in …
```

Sg 6422 proxy logging missing exception information

---

python/tk_desktop/desktop_engine_project_implementation.py
python/tk_desktop/desktop_window.py

A regression in the last release introduced a bug where it errored when shutting down the project python process.
Also fixes a typo in a comment.
```
...
File "/Users/philips1/source_code/tk-desktop/python/tk_desktop/desktop_engine_project_implementation.py", line 367, in _emit_log_message
self._proxy.call_no_response(
AttributeError: 'DesktopEngineProjectImplementation' object has no attribute '_proxy'
```
There was a typo where it was calling `self._proxy` instead of `self._project_comm`.
Upon fixing that, it turned out it should also be checking if the `_project_comm` is still connected before trying to log.

Fixes a bug with closing a Python process

---

python/tk_desktop/setup_project.py

The Configuration Setup help page has changed location. We now point to the new page.

Fixed url for documentation page

---

style.qss

This fixes a styling issue on SG Desktop with PySide2 where pressing the back button on the project page, would cause a dark background on the button to appear. Where as with PySide (1) the icon would indent but the background wouldn't change. 
This also cause other visual oddities as there are two "spacer" buttons inserted on each side of the bar, which as far as I can see do nothing, but it meant these also when dark when pressed, where as before the user didn't know they were pressing them as there was no visual clue. I don't know why these buttons exist, it seems an actual spacer could have been used, but I didn't change this as I don't know the reasons behind it. The styling fix applies to them as well so they go back to being invisible.
Also it became apparent on fixing the …

SG-17723 Fixes the styling issues with PySide2 around the project back button.

---

python/tk_desktop/command_panel/recent_button.py
python/tk_desktop/command_panel/recent_list.py

The recent items list was cropping some of the text on the items depending on the size of the window when you opened the project. This is it in an extreme state where the window was really small when clicking on the project, and then expanded after loading.
This fix does the following:
- Makes the buttons stretch out as the window stretches rather than keeping them fixed.
- Makes the text stay aligned to the top, so that it doesn't display at varying heights when the text for some buttons goes onto multiple lines.
- Reduces the spacing between the buttons slightly (by 1px) so that the impact of having a smaller window is slightly reduced on the cropping.
In summary the cropping of text still happens, but it is less severe, and expanding the window allows the items have enough room to show …

SG-17782 Adjusts some of the spacing between recent items.

---

python/tk_desktop/desktop_window.py
python/tk_desktop/ui/about_screen.py
python/tk_desktop/ui/resources_rc.py
python/utils/bootstrap_utilities.py
resources/about_screen.ui

The about box now shows the Python version, only if the build supports both Python 2 and 3. 
As for the logging, it looks like this:
```
Python
======
Executable: /Applications/Shotgun.app/Contents/MacOS/Shotgun
Version: 2.7.17
sys.path:
- /Users/boismej/gitlocal/tk-framework-desktopstartup/python
- /Applications/Shotgun.app/Contents/Resources/Desktop/Python
- /Applications/Shotgun.app/Contents/Resources/Python/lib/python27.zip
- /Applications/Shotgun.app/Contents/Resources/Python/lib/python2.7
- /Applications/Shotgun.app/Contents/Resources/Python/lib/python2.7/plat-darwin
- /Applications/Shotgun.app/Contents/Resources/Python/lib/python2.7/plat-mac
- /Applications/Shotgun.app/Contents/Resources/Python/lib/python2.7/plat-mac/lib-scriptpackages
- …
```

SG:18139: Python version in about box.

---

info.yml
python/tk_desktop/desktop_window.py
python/tk_desktop/setup_project.py

Reactivates the admin UI in Python 3.
I've also removed code that broke the admin UI on Linux and Windows with PySide2 and which wasn't required with PySide 1. Less code, good!

SG-13270: adminui in python3

---

info.yml
python/tk_desktop/desktop_engine_site_implementation.py

This removes the check that only allows browser integration for Python2. It also bumps the minimum version for the desktopserver requirement to the version that supports Python3

SG-16894 Enable browser integration for python3

---

python/tk_desktop/command_panel/command_panel.py

Recent items were not being stored when in Python 3 due to the way we were trying to pickle the datetime objects before saving them with `QSettings`.
I looked into applying the fix at the shotgunutils side, and whilst it was possible there were other complications and things to consider. In the end it was simpler to store string representations of the datetime instead.
This code handles loading both datetime object and string dates which it then converts back into datetime objects for use during run time.
You will get an error if you downgrade desktop as the old desktop will not know how to handle the string format. However this error is largely silent, it only appears to show if you launched from a terminal, and the rest of the recents items that weren't stored with a string format do …

SG-17970 Fixes recent items not showing.

---

python/tk_desktop/desktop_engine_project_implementation.py
python/tk_desktop/desktop_engine_site_implementation.py

In the tk-desktop engine implementations we are calling `destory_engine()` directly instead of calling `destroy()` and letting it call `destroy_engine()`. As a result, a lot of the normal shut down procedures are not being called. 
This solves the problem in the ticket that the `destroy_app()` method on apps was not being called. The other thing mentioned in the ticket was that `closeEvent` is not called on the widget. This fix does not solve that problem.

SG-18277 Engine's destroy method not called

---

python/tk_desktop/desktop_engine_project_implementation.py

Fixes an issue that was introduced with the fix for the project `QApplication` stealing focus on Mac.
That fix introduced an an issue where the keyboard input couldn't be registered with any of the launched apps. This was because the `QApplication` was permanently in the background.
The fix is to now move it to the foreground when we run an app.

SG-18612 fix for no keyboard input on mac

---

python/tk_desktop/desktop_window.py
python/tk_desktop/extensions/darwin_python2/__init__.py
python/tk_desktop/extensions/darwin_python3/__init__.py
python/tk_desktop/extensions/linux_python2_qt4/__init__.py

When another site tries to connect to browser integration in Shotgun Desktop, the site switching dialog did not appear in Python 3. This was because the site switching code had been disabled back when the browser integration was not Python 3 compatible, but we forgot to turn it back on. So now it is.
I also noticed an issue where the site switching dialog would not be focussed on macOS. Turns out we were importing a module from a directory without a `__init__.py` on macOS, so I've added it. On Linux the the `__init__.py` file was present and on Windows there is no extension module to load.

SG-18905: Site switching fix

---

python/tk_desktop/console.py

I came across an issue on my Windows VM, where it was loading an old position setting value created in PySide, and trying to pass it to a PySide2 method, which errored and caused desktop not to start.
Normally the loading of the value in the settings manager would fail and the settings manager would gracefully handle it and return the default value. However there seemed to be something different about my vm setup that caused it to be able to load the old PySide value, and so an error was raised.
I didn't get to the bottom of what was different on my machine, but potentially this might happen to others, so it seemed better to fix it anyway.

SG-19710 Fixes error loading console position and size.

---

engine.py
python/tk_desktop/desktop_window.py

The Shotgun Desktop will now be displayed unpinned by default the first time it is launched. This will reduce the confusion of first time users who do not understand where the app goes after the splash screen disappears.
Also, when a user clicks on the X or red button of the dialog, a pop-up will be shown the very first time letting the user know the app is now in the tray.
Finally, unhandled exceptions are now going to be logged. (FINALLY!!!!)
UPDATE after some QA tests:
I've rewired the chain of quitting operations in the Desktop. The Quit option in the menu instead calls quit on the QApplication and the handle_quit_action has been turned into a slot for the QApplication.aboutToQuit signal. This was necessary to handle macOS quirkyness when hitting CMD-Q properly. See the comments in …

SS-18239: undocked by default

---

python/tk_desktop/licenses.html
software_credits

This updates the about box licensing to include additional Python 3rd party licenses that we are bundling.
Also updates the component links to point to new software credit files and removes those that don't exist anymore.
I've also added div tags to the licence html to make it easier to collapse the licence sections in an editor.

SG-19789 Update licensing

---

python/tk_desktop/desktop_window.py

If the previous window position was stored as a PySide object it can sometimes end up getting through the `settings_manager.retrieve` and passed to PySide2, on which it then fails. This now just gracefully gives up on restoring the window position in this case.
Still needs testing, but getting this scenario is difficult and its not entirely clear how to replicate.

Fix for restoring window position error

---

tests/test_about_box.py

Adds tests that check that all the URLs in the licences.html is a valid link, and checks that certain expected software credit link exist.

Testing licence urls

---

engine.py
python/tk_desktop/licenses.html

In order to assert a creation of _host_info attribute for each class or subclass instances, I added the method `__new__` to `DesktopEngine` class.

SG-11032 [tk-desktop] doesn't implement the host_info

---

python/tk_desktop/desktop_engine_project_implementation.py

This checks if Qt is already running and if a QApplication has been previously initialized. If not, it creates a Qt app instance. This fixes the RuntimeError that occurs silently in the desktop bootstrap when create any Qt application in the engine_init core hook.

SG-31715 Engine Init Hook Cant Run QtguiQmessagebox

---

python/tk_desktop/notifications/__init__.py
python/tk_desktop/notifications/centos7_deprecation_notification.py
python/tk_desktop/notifications/notification_manager.py
python/tk_desktop/notifications/platform_os_release.py
tests/test_notifications.py
tests/test_notifications_el7.py

Create a new banner to announce the end of support for CentOS 7.
Display the banner only on Linux. But not on Rocky 8 or any EL8. We display the banner on:
- Any Linux that is not EL
- Any EL7
- Any unknown Linux

SG-26914 Add banner centos 7 deprecation notice

---

info.yml
python/tk_desktop/no_apps_installed_overlay.py
python/tk_desktop/ui/no_apps_installed_overlay.py
resources/no_apps_installed_overlay.ui

The CustomNonProjectEntity23 entity is long gone and has been replaced by the Software entity since SG version 7.2.
Fixing the behavior by re-aligning the function behavior with the implementation in tk-multi-launchapp: https://github.com/shotgunsoftware/tk-multi-launchapp/blob/v0.13.0/python/tk_multi_launchapp/software_entity_launcher.py#L204

SG-35333 Fix broken NoAppsInstalledOverlay layout

---

python/tk_desktop/rpc.py

Increase the existing error handling to have more use cases. This will prevent flaky tests on CI.

SG-35325 Prevent flaky tests

---

python/tk_desktop/desktop_engine_site_implementation.py
python/tk_desktop/desktop_window.py

Move the logic for phase 1 (update last accessed timestamp in SG)  when launching of the app proxy for a project in a `QThread` ~~[Background Task Manager](https://developers.shotgridsoftware.com/tk-framework-shotgunutils/task_manager.html)~~ so it doesn't block the UI.

SG-36162 Refactor __launch_app_proxy_for_project in a QThread

---

python/tk_desktop/desktop_engine_site_implementation.py
tests/test_command_panel.py

- The error happens because LooseVersion("v1.9.1") is parsed as ["v1", 9, 1], while LooseVersion("1.1.0") is ["1", 1, 0]. The comparison fails when Python tries to compare "v1" (a string) with 1 (an integer). Adding the "v" prefix would make them comparable.
- With the fix, Desktop launches without any issues.

SG-38064 Inconsistent comparison - bug fix

---

python/tk_desktop/desktop_engine_site_implementation.py
python/tk_desktop/desktop_window.py
tests/test_command_panel.py

This PR removes dead code related to uses_legacy_authentication.
This cleanup follows a previously identified issue where LooseVersion("v1.9.1") was parsed as ["v1", 9, 1], which is described in more detail in that earlier [PR](https://github.com/shotgunsoftware/tk-desktop/pull/194).
Rather than removing the unused code at the time, we opted to fix the issue by updating the version string to avoid the problematic comparison. This PR now completes the process by removing the obsolete logic that was originally tied to that condition.

SG-38672 Removed dead authentication code

---

python/tk_desktop/command_panel/command_panel.py
python/tk_desktop/project_model.py
tests/test_command_panel.py

This pull request updates the handling of timestamps throughout the codebase to use timezone-aware `datetime` objects, ensuring consistency and preventing potential issues with naive `datetime` usage. The changes also include updates to corresponding test cases.
* [`python/tk_desktop/command_panel/command_panel.py`](diffhunk://#diff-6d80519da321fc7bd0de525e8cb94e8efe7bec998484024da4e64518b40df332L188-R188): Modified the `_update_recents_list` method to use `datetime.now(timezone.utc)` instead of `datetime.utcnow()` for creating timezone-aware timestamps.
* [`python/tk_desktop/project_model.py`](diffhunk://#diff-6cf3b0c8c33231d62e9107b7f2b39f02af810280b50acbbe241bc2b4ef95fb3bL324-R324): Updated the `update_project_accessed_time` method to use `datetime.now(datetime.timezone.utc)` for …

SG-37924 Replace utcnow() for Python 3.12
